# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: MediaStack.Guide
site_url: https://mediastack.guide/

repo_name: media-stack
repo_url: https://github.com/geekau/media-stack

plugins:
  - search
  - glightbox
#  - git-committers:
#      repository: geekau/media-stack
#      branch: main

nav:
  - Home:                            index.md
  - Introduction:
    - Intro to MediaStack:           intro/mediastack.md
    - Applications and Their Roles:  intro/application-roles.md
    - Installing Docker on Host OS:  intro/install-docker.md
    - Organising Your Media Library: intro/media-library.md
    - Docker Filesystems / Folders:  intro/docker-filesystems.md
    - Download Docker Build Files:   intro/download-mediastack.md
  - Installing Docker Apps:
    - Configuring Environment:       install/environment-file.md
    - Installing Apps Individually:  install/individual-install.md
    - Installing Apps Collectively:  install/collective-install.md
    - Configuring Environment:       install/environment-file.md
    - Portainer - Docker GUI:        install/portainer.md
  - Configure Docker Apps:
    - Download Clients:              configure/download-clients.md
    - "*ARR (starr) Applications":   configure/arr-applications.md
    - Jellyfin Media Server:         configure/jellyfin.md
    - Jellyseerr - Request Media:    configure/jellyseerr.md
    - SWAG Reverse Proxy:            configure/swag.md
    - DDNS-Updater:                  configure/ddns-updater.md
    - Cloudflare Zero Trust:         configure/cloudflare-zero-trust.md
    - Cloudflare Domain Management:  configure/cloudflare-domains.md
  - Contributing to MediaStack:
    - Contributing:                  contributing/contributing.md


theme:
  name: material

  features:
#  - content.tabs.link
  - navigation.instant
  - navigation.tracking
#  - navigation.top
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.sections
#  - navigation.expand
  - navigation.prune
  - navigation.indexes
  - toc.follow
#  - toc.integrate
  - search.suggest
  - search.highlight
  - header.autohide

  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: deep purple
    accent: light green
    toggle:
      icon: material/lightbulb
      name: Switch to Dark Mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: yellow
    accent: red
    toggle:
      icon: material/lightbulb-outline
      name: Switch to Light Mode

  icon:
    logo: fontawesome/solid/photo-film
    repo: fontawesome/brands/github
    admonition:
      note:     fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info:     fontawesome/solid/circle-info
      tip:      fontawesome/solid/bullhorn
      success:  fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning:  fontawesome/solid/triangle-exclamation
      failure:  fontawesome/solid/bomb
      danger:   fontawesome/solid/skull
      bug:      fontawesome/solid/robot
      example:  fontawesome/solid/flask
      quote:    fontawesome/solid/quote-left
  
markdown_extensions:
  - admonition
  - pymdownx.betterem
  - pymdownx.caret: {smart_insert: true, insert: true, superscript: true}
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight: {auto_title: true, anchor_linenums: true}
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
  - pymdownx.tasklist: {custom_checkbox: true}
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      title: "On This Page:"
      toc_depth: 3
      permalink: true
      permalink_title: "Permanent Link <Anchor>"
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascript/extra.js

extra:
  consent:
    title: Cookie Consent
    description: >- 
      We use cookies to recognise your repeated visits and preferences, as well as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to make our documentation better.

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/geekau/MediaStack.Guide
      name: "GitHub: MediaStack.Guide"

    - icon: fontawesome/brands/github
      link: https://github.com/geekau/media-stack
      name: "GitHub: media-stack"

    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/squidfunk
      name: "Twitter: squidfunk"

copyright: >
  Copyright &copy; 2023 - <a href="https://MediaStack.Guide">MediaStack.Guide</a> - <a href="#__consent">Update Change Cookie Settings</a>
