# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: MediaStack.Guide
site_url: https://mediastack.guide/
site_description: >
  Quick-start guide to set up a full VPN encrypted streaming media service, with reverse-proxy / MFA access from the Internet, for Linux, Windows, Synology NAS, and more...   Full Docker deployment for Jellyfin, Jellyseerr, Gluetun, DDNS-Updater, Prowlarr, Radarr, Sonarr, Lidarr, Mylar, Readarr, Whisparr, Bazarr, qBittorrent, SABnzbd, Unpackerr, SWAG, Heimdall, Authelia, Flaresolverr, and Portainer.

repo_name: mediastack.guide
repo_url: https://github.com/geekau/mediastack.guide
edit_uri: blob/main/docs/

plugins:
  - search
  - glightbox
  - git-revision-date-localized:
      enable_creation_date: false
#  - typeset

nav:
  - Home:                            index.md
  - Preparation:
    - MediaStack Applications:       preparation/applications-roles.md
    - Installing Docker:             preparation/install-docker.md
    - Docker Filesystems / Folders:  preparation/docker-filesystems.md
    - Prepare Media Library:         preparation/media-library.md
    - Docker Compose Files:          preparation/compose-files.md
  - Installation:
    - Configuring Environment:       installation/environment-file.md
    - Installing Apps Individually:  installation/individual-install.md
    - Installing Apps Collectively:  installation/collective-install.md
    - Configuring Environment:       installation/environment-file.md
    - Portainer - Docker GUI:        installation/portainer.md
  - Configuration:
    - Download Clients:              configuration/download-clients.md
    - "*ARR (starr) Applications":   configuration/arr-applications.md
    - Jellyfin Media Server:         configuration/jellyfin.md
    - Jellyseerr - Request Media:    configuration/jellyseerr.md
    - SWAG Reverse Proxy:            configuration/swag.md
    - DDNS-Updater:                  configuration/ddns-updater.md
    - Cloudflare Zero Trust:         configuration/cloudflare-zero-trust.md
    - Cloudflare Domain Management:  configuration/cloudflare-domains.md
  - Contributing to MediaStack:
    - Contributing:                  contributing/contributing.md
    - Template:                      contributing/doc-template.md


theme:
  name: material
  custom_dir: overrides
  favicon: assets/favicon.ico

  features:
  - announce.dismiss
  - content.action.edit
  - content.action.view
  - content.code.annotate
  - content.code.copy
  - content.tabs.link
  - navigation.instant
  - navigation.tracking
  - navigation.top
  - navigation.footer
  - navigation.tabs
  - navigation.sections
  - navigation.expand
  - navigation.prune
  - navigation.indexes
  - toc.follow
  - toc.integrate
  - search.suggest
  - search.highlight

  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: deep purple
    accent: light green
    toggle:
      icon: material/lightbulb
      name: Switch to Dark Mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: yellow
    accent: red
    toggle:
      icon: material/lightbulb-outline
      name: Switch to Light Mode

  icon:
    logo: assets/header-logo
    repo: fontawesome/brands/github
    admonition:
      note:     fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info:     fontawesome/solid/circle-info
      tip:      fontawesome/solid/bullhorn
      success:  fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning:  fontawesome/solid/triangle-exclamation
      failure:  fontawesome/solid/bomb
      danger:   fontawesome/solid/skull
      bug:      fontawesome/solid/robot
      example:  fontawesome/solid/flask
      quote:    fontawesome/solid/quote-left

markdown_extensions:
  - admonition
  - pymdownx.betterem
  - pymdownx.caret: {smart_insert: true, insert: true, superscript: true}
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight: {auto_title: true, anchor_linenums: true}
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
  - pymdownx.tasklist: {custom_checkbox: true}
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      title: "On This Page:"
      toc_depth: 4
      permalink: true
      permalink_title: "Permanent Link <Anchor>"
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascript/extra.js

extra:
  version:
    provider: stable
  consent:
    title: Cookie Consent
    description: >- 
      We use cookies to recognise your repeated visits and preferences, as well as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to make our documentation better.

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/geekau/MediaStack.Guide
      name: "GitHub: MediaStack.Guide"

    - icon: fontawesome/brands/github
      link: https://github.com/geekau/media-stack
      name: "GitHub: media-stack"

    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/squidfunk
      name: "Twitter: squidfunk"

copyright: >
  Copyright &copy; 2023 - <a href="https://MediaStack.Guide">MediaStack.Guide</a> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ( &nbsp;<a href="#__consent">Update Change Cookie Settings</a> &nbsp;)
