# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: MediaStack.Guide
site_url: https://mediastack.guide/

repo_name: media-stack
repo_url: https://github.com/geekau/media-stack

plugins:
  - search
  - glightbox
#  - git-committers:
#      repository: geekau/media-stack
#      branch: main


nav:
  - Home: index.md
  - Introduction:
    - Intro to MediaStack:          intro/intro.md
    - Applications and Their Roles: intro/applicationroles.md
    - Installing Docker on Host OS: intro/docker.md
    - Docker Filesystems / Folders: intro/filesystems.md
    - Download Docker Build Files:  intro/download.md
  - Installing Docker Apps:
    - Configuring Environment:      install/environment.md
    - Installing Apps Individually: install/individualinstall.md
    - Installing Apps Collectively: install/collectiveinstall.md
    - Configuring Environment:      install/environment.md
    - installation/deletethis.md
  - Contributing to MediaStack:
    - testing.md
    - contributing.md
    - Download: download.md
    - environment.md
    - quick-build.md
    - test.md

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
    admonition:
      note:     fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info:     fontawesome/solid/circle-info
      tip:      fontawesome/solid/bullhorn
      success:  fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning:  fontawesome/solid/triangle-exclamation
      failure:  fontawesome/solid/bomb
      danger:   fontawesome/solid/skull
      bug:      fontawesome/solid/robot
      example:  fontawesome/solid/flask
      quote:    fontawesome/solid/quote-left
  
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: blue
    accent: red
    toggle:
      icon: material/lightbulb
      name: Switch to Dark Mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: yellow
    accent: red
    toggle:
      icon: material/lightbulb-outline
      name: Switch to Light Mode

    features:
    - content.tabs.link
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
#    - navigation.prune
#    - navigation.indexes
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.highlight
    - header.autohide

markdown_extensions:
  - admonition
  - pymdownx.betterem
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret:
      smart_insert: true
      insert: true
      superscript: true
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      title: "On This Page:"
      toc_depth: 3
      permalink: true
      permalink_title: "Permanent Link <Anchor>"
      slugify: !!python/name:pymdownx.slugs.uslugify



#  custom_dir: overrides

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js


extra:
  consent:
    title: Cookie Consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to make our documentation better.

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/geekau/MediaStack.Guide
      name: "GitHub: MediaStack.Guide"

    - icon: fontawesome/brands/github
      link: https://github.com/geekau/media-stack
      name: "GitHub: media-stack"

    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/squidfunk
      name: "Twitter: squidfunk"

copyright: >
  Copyright &copy; 2023 - MediaStack.Guide – <a href="#__consent">Change Cookie Settings</a>