# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: MediaStack.Guide
site_url: https://mediastack.guide/

repo_url: https://github.com/geekau/media-stack
repo_name: media-stack

plugins:
  - search
  - git-committers:
      repository: geekau/media-stack
      branch: main

nav:
  - Home: index.md
  - Introduction:
    - Intro to MediaStack:          starting/intro.md
    - Applications and Their Roles: starting/applicationroles.md
    - Installing Docker on Host OS: starting/docker.md
    - Docker Filesystems / Folders: starting/filesystems.md
    - Download Docker Build Files:  starting/download.md
  - Installing Docker Apps:
    - Configuring Environment:      installation/environment.md
    - Installing Apps Individually: installation/individualinstall.md
    - Installing Apps Collectively: installation/collectiveinstall.md
    - Configuring Environment:      installation/environment.md
    - installation/deletethis.md
  - Contributing to MediaStack:
    - testing.md
    - contributing.md
    - Download: download.md
    - environment.md
    - quick-build.md
    - test.md

theme:
  name: material
  
  palette: 
  - scheme: slate
    toggle:
      icon: material/brightness-7 
      name: Switch to Light Mode
  - scheme: default
    toggle:
      icon: material/brightness-4
      name: Switch to Dark Mode
    features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - header.autohide


#  custom_dir: overrides

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js


extra:
  consent:
    title: Cookie Consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to make our documentation better.

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/geekau/MediaStack.Guide
      name: "GitHub: MediaStack.Guide"

    - icon: fontawesome/brands/github
      link: https://github.com/geekau/media-stack
      name: "GitHub: media-stack"

    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/squidfunk
      name: "Twitter: squidfunk"

copyright: >
  Copyright &copy; 2023 - MediaStack.Guide – <a href="#__consent">Change Cookie Settings</a>